Repository osuAkatsuki/interns-backend, pull requests merged in 2023-04, with the labels that each got.

#2 bootstrap database seed migrations
  Makefile
  database/migrations/00001_create_accounts_table.down.sql
  database/migrations/00001_create_accounts_table.up.sql
  database/migrations/00002_create_channels_table.down.sql
  database/migrations/00002_create_channels_table.up.sql
  database/migrations/00003_create_stats_table.down.sql
  database/migrations/00003_create_stats_table.up.sql
  scripts/bootstrap.sh
  scripts/migrate-db.sh
  scripts/seed-db.sh
Labels: enhancement

#6 add routing for osu.ppy.sh
  nginx.conf
  server/main.py
Labels: enhancement

#11 Started Implementing Commands
  server/command_handler.py
  server/packet_handlers.py
Labels: enhancement

#15 Spectator packet handlers
  server/packet_handlers.py
  server/packets.py
  server/repositories/sessions.py
  server/repositories/spectators.py
Labels: enhancement

#16 mostly working spectator & related fixes/changes
  database/migrations/00005_create_scores_table.down.sql
  scripts/sign_up.py
  server/main.py
  server/packet_handlers.py
  server/packets.py
  server/repositories/scores.py
  server/repositories/sessions.py
  server/repositories/spectators.py
Labels: bug, enhancement

#18 anti-ghosting support (allow ghosting after a certain ping delta)
  server/main.py
Labels: enhancement

#17 Add packet handler for request user stats
  server/packet_handlers.py
  server/packets.py
Labels: enhancement

#20 beatmaps repository & db migrations
  database/migrations/00006_create_beatmaps_table.down.sql
  database/migrations/00006_create_beatmaps_table.up.sql
  server/repositories/beatmaps.py
Labels: enhancement

#8 base for getscores handler
  docker-compose.yml
  requirements.txt
  server/adapters/osu_api_v2.py
  server/clients.py
  server/logger.py
  server/main.py
  server/repositories/accounts.py
  server/repositories/beatmaps.py
  server/repositories/scores.py
  server/settings.py
Labels: enhancement

#19 refactor commands into decorated coroutines separated into a module
  server/command_handlers.py
  server/packet_handlers.py
Labels: code quality

#22 Added S3 Upload & Download Functionality
  .env.example
  docker-compose.yml
  requirements-dev.txt
  requirements.txt
  server/adapters/s3.py
  server/clients.py
  server/main.py
  server/settings.py
Labels: enhancement

#23 implement some basic privileges & clean up usage of presences
  scripts/sign_up.py
  server/command_handlers.py
  server/main.py
  server/packet_handlers.py
  server/packets.py
  server/privileges.py
  server/repositories/sessions.py
Labels: enhancement

#26 finish accounts service
  scripts/sign_up.py
  server/errors.py
  server/repositories/accounts.py
  server/services/accounts.py
  server/validation.py
Labels: enhancement

#9 base for score submission handler
  database/migrations/00004_create_relationships_table.down.sql
  database/migrations/00005_create_scores_table.up.sql
  docker-compose.yml
  requirements.txt
  scripts/sign_up.py
  server/main.py
  server/repositories/beatmaps.py
  server/repositories/scores.py
  server/repositories/stats.py
Labels: enhancement
