Repository osuAkatsuki/interns-backend, pull requests merged in 2023-05, with the labels that each got.

#37 Multiplayer interactions
  requirements.txt
  server/clients.py
  server/errors.py
  server/packet_handlers.py
  server/repositories/multiplayer_match_ids.py
  server/repositories/multiplayer_matches.py
  server/repositories/sessions.py
  server/services/multiplayer_matches.py
Labels: enhancement

#38 Login attempts repository
  server/repositories/login_attempts.py
Labels: enhancement

#39 Multiplayer match creation nearly functional™️, chat fixes
  database/seeds/00002_create_more_baseline_channels.down.sql
  database/seeds/00002_create_more_baseline_channels.up.sql
  server/main.py
  server/packet_handlers.py
  server/packets.py
  server/privileges.py
  server/repositories/channels.py
  server/repositories/multiplayer_matches.py
  server/repositories/multiplayer_slots.py
  server/repositories/sessions.py
  server/services/multiplayer_matches.py
Labels: enhancement

#45 Screenshot uploading from osu! client
  server/adapters/s3.py
  server/main.py
  server/services/screenshots.py
Labels: enhancement

#46 osu! clans repository layer written
  database/migrations/00010_create_clans_table.down.sql
  database/migrations/00010_create_clans_table.up.sql
  server/repositories/clans.py
Labels: enhancement

#33 PP calculation upon score submission
  Dockerfile
  requirements.txt
  server/adapters/osu_api_v2.py
  server/main.py
  server/packets.py
  server/performance.py
  server/repositories/scores.py
  server/repositories/stats.py
Labels: enhancement

#44 Create beatmaps service layer with jit logic; track bancho ranked status & updated_at separately
  database/migrations/00011_add_columns_to_beatmaps_table.down.sql
  database/migrations/00011_add_columns_to_beatmaps_table.up.sql
  server/adapters/osu_api_v2.py
  server/errors.py
  server/main.py
  server/repositories/beatmaps.py
  server/services/beatmaps.py
Labels: enhancement

#41 handle privilege checks and #lobby for channel info on login
  server/main.py
  server/packets.py
Labels: bug, enhancement

#48 user achievements repository
  database/migrations/00012_create_user_achievements_table.down.sql
  database/migrations/00012_create_user_achievements_table.up.sql
  server/main.py
  server/repositories/achievements.py
  server/repositories/user_achievements.py
Labels: enhancement

#49 clean up packets a bit; share write match logic
  server/packets.py
Labels: code quality

#30 Achievement handlers
  database/seeds/00003_insert_base_achievements.down.sql
  database/seeds/00003_insert_base_achievements.up.sql
  server/achievement_handlers.py
  server/main.py
Labels: enhancement

#50 Relax & autopilot support
  scripts/sign_up.py
  server/game_modes.py
  server/main.py
  server/packet_handlers.py
Labels: enhancement

#53 split up osu! apis into separate files (clean up main.py)
  server/adapters/redis.py
  server/api/osu/bancho.py
  server/api/osu/web.py
  server/clients.py
  server/lifecycle.py
  server/main.py
Labels: code quality

#52 Add the ability for users to set "away messages", autoreplies when AFK
  app/api/osu/bancho.py
  app/packet_handlers.py
  app/repositories/sessions.py
Labels: enhancement

#57 Finish create multiplayer match implementation; temp channels; fix public message channel fetching & broadcast; channels created/updated at defaults
  app/api/osu/bancho.py
  app/packet_handlers.py
  app/packets.py
  app/repositories/channels.py
  app/repositories/multiplayer_match_ids.py
  app/repositories/multiplayer_slots.py
  app/repositories/sessions.py
  app/services/multiplayer_matches.py
  database/migrations/00013_add_temporary_column_to_channels_table.down.sql
  database/migrations/00013_add_temporary_column_to_channels_table.up.sql
  database/migrations/00014_add_default_to_timestamp_channel_columns.down.sql
  database/migrations/00014_add_default_to_timestamp_channel_columns.up.sql
Labels: bug, enhancement

#63 Integrate service with Akatsuki k8s
  .env.example
  .github/workflows/staging-deploy.yml
  Makefile
  app/lifecycle.py
  app/settings.py
  chart/values.yaml
  database/seeds/00002_create_more_baseline_channels.up.sql
  database/seeds/00003_insert_base_achievements.down.sql
  docker-compose.yml
Labels: enhancement

#58 Add ability to change multiplayer slot
  app/packet_handlers.py
  app/repositories/multiplayer_slots.py
  app/services/multiplayer_matches.py
Labels: enhancement

#65 Fix match slots
  app/packet_handlers.py
Labels: bug

#69 get all ranked status enums; map between them; fix getscores.php ranked status
  app/api/osu/web.py
  app/ranked_statuses.py
  app/repositories/beatmaps.py
  app/services/beatmaps.py
Labels: bug

#68 Implement joining a multiplayer match
  app/clients.py
  app/packet_handlers.py
Labels: enhancement

#61 REST APIs for fetching scores; related plumbing
  app/api/rest/__init__.py
  app/api/rest/v1/scores/controllers.py
  app/api/rest/v1/scores/models.py
  app/errors.py
  app/repositories/scores.py
  app/services/scores.py
Labels: enhancement

#62 Add osu-getreplay.php web handler
  app/api/osu/web.py
Labels: enhancement

#76 feat: some slot status handlers + change match settings
  app/packet_handlers.py
  app/packets.py
Labels: enhancement

#78 INTRN-81: leaderboard type filters
  app/api/osu/web.py
  app/repositories/scores.py
Labels: enhancement

#75 INTRN-170: implement score submission status & related functionality
  app/api/osu/web.py
  app/repositories/scores.py
Labels: enhancement

#60 INTRN-158: Respond to score submission with charts & achievements
  app/api/osu/web.py
  app/repositories/achievements.py
  app/repositories/beatmaps.py
Labels: enhancement

#84 INTRN-177: Fix automated doc generation for host routers
  app/fastapi_utils.py
  app/main.py
Labels: bug

#83 INTRN-176: Global & country overall rankings
  app/api/osu/bancho.py
  app/api/osu/web.py
  app/mods.py
  app/packet_handlers.py
  app/ranking.py
  app/repositories/scores.py
Labels: enhancement

#85 INTRN-44: (and others); finish multiplayer packets
  app/packet_handlers.py
  app/packets.py
  app/repositories/multiplayer_slots.py
Labels: enhancement

#86 INTRN-141: Clan Members Repository
  app/packet_handlers.py
  app/repositories/clan_invites.py
  app/repositories/clan_members.py
  database/migrations/00017_create_clan_members_table.down.sql
  database/migrations/00017_create_clan_members_table.up.sql
Labels: enhancement

#89 Silence End Added to Accounts
  app/packets.py
  app/repositories/accounts.py
  app/repositories/multiplayer_slots.py
  database/migrations/00018_alter_accounts_table.down.sql
  database/migrations/00018_alter_accounts_table.up.sql
Labels: enhancement

#91 INTRN-179: handle !help in public channel special case
  app/packet_handlers.py
Labels: bug

#92 INTRN-216: cache docker image build steps in GHA CI
  .github/workflows/staging-deploy.yml
Labels: performance

#93 INTRN-218: Rewrite logger; notably handling of uvicorn loggers and exception formatting
  app/adapters/osu_api_v2.py
  app/logger.py
  app/main.py
  requirements.txt
Labels: bug, enhancement, code quality

#95 INTRN-131: add logic for #spectator channel to spectator join
  app/packet_handlers.py
Labels: enhancement

#96 INTRN-133: Stop spectating channel handling
  app/packet_handlers.py
Labels: enhancement

#99 bug fix, spelling
  app/repositories/clan_members.py
Labels: bug

#102 INTRN-219: ping time tracking
  app/api/osu/bancho.py
  app/packet_handlers.py
  app/repositories/sessions.py
Labels: enhancement

#101 INTRN-89: Beatmap ranked status editing commands
  app/adapters/osu_api_v2.py
  app/api/osu/bancho.py
  app/commands.py
  app/packet_handlers.py
  app/repositories/sessions.py
Labels: enhancement

#97 INTRN-93: Score frame, replay frame, and replay frame bundle serialization & deserialize
  app/packet_handlers.py
  app/packets.py
Labels: enhancement, code quality

#104 Silence End Handler
  app/api/osu/bancho.py
  app/packets.py
Labels: enhancement

#106 INTRN-214: New accounts columns for akatsuki support
  database/migrations/00019_add_akatsuki_accounts_columns.down.sql
  database/migrations/00019_add_akatsuki_accounts_columns.up.sql
Labels: enhancement

#108 INTRN-225: allow multiple sessions to login & add the concept of a primary session
  app/api/osu/bancho.py
  app/api/osu/web.py
  app/packet_handlers.py
  app/repositories/sessions.py
Labels: enhancement

#109 INTRN-226: tournament client packets
  app/packet_handlers.py
Labels: enhancement

#110 INTRN-227: block non friend dms
  app/api/osu/bancho.py
  app/packet_handlers.py
  app/packets.py
  app/repositories/sessions.py
Labels: enhancement

#111 INTRN-230: work on friends, silences, and an Unset type for filter params
  app/api/osu/bancho.py
  app/packet_handlers.py
  app/packets.py
  app/repositories/accounts.py
  app/services/accounts.py
  app/typing.py
Labels: enhancement

#112 INTRN-232: implement base for command sets
  app/commands.py
  app/packet_handlers.py
Labels: enhancement
